// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg-16P_YW8j1NTYx02S4d7z9pA0mwdCgs',
    appId: '1:187685503651:web:1a968c72a2cb782efc7516',
    messagingSenderId: '187685503651',
    projectId: 'lepton-dujo',
    authDomain: 'lepton-dujo.firebaseapp.com',
    databaseURL: 'https://lepton-dujo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lepton-dujo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv2kTuUgw_Jqy-fqgA1DVtnneR4lpxvH0',
    appId: '1:187685503651:android:ef573560e11a61befc7516',
    messagingSenderId: '187685503651',
    projectId: 'lepton-dujo',
    databaseURL: 'https://lepton-dujo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lepton-dujo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvzMl6S-XW9EZ_2Zwo0BgGZep9NHKZL4I',
    appId: '1:187685503651:ios:35ee1b81e89dc763fc7516',
    messagingSenderId: '187685503651',
    projectId: 'lepton-dujo',
    databaseURL: 'https://lepton-dujo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lepton-dujo.appspot.com',
    androidClientId: '187685503651-sdidi3encdk1nhvtgjtk0mg6m472ba00.apps.googleusercontent.com',
    iosClientId: '187685503651-fmkaaahk05cvtmnmonjqjnsjhaek9gtp.apps.googleusercontent.com',
    iosBundleId: 'com.example.dujoDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvzMl6S-XW9EZ_2Zwo0BgGZep9NHKZL4I',
    appId: '1:187685503651:ios:35ee1b81e89dc763fc7516',
    messagingSenderId: '187685503651',
    projectId: 'lepton-dujo',
    databaseURL: 'https://lepton-dujo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lepton-dujo.appspot.com',
    androidClientId: '187685503651-sdidi3encdk1nhvtgjtk0mg6m472ba00.apps.googleusercontent.com',
    iosClientId: '187685503651-fmkaaahk05cvtmnmonjqjnsjhaek9gtp.apps.googleusercontent.com',
    iosBundleId: 'com.example.dujoDemoApp',
  );
}
